#!/usr/bin/env ruby

# Copyright © 2009 Johan Kiviniemi
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

begin
  require 'rubygems'
rescue LoadError
  # Ignore.
end

require 'cgi'
require 'json'
require 'open-uri'
require 'pp'
require 'readline'

def exec_or_die *args
  begin
    exec *args
  rescue => e
    $stderr.puts "Error running #{args.inspect}: #{e.class}: #{e}"
  ensure
    exit 1
  end
end

loop do
  yql = Readline.readline '> '
  break if yql.nil?
  Readline::HISTORY.push yql

  uri = 'http://query.yahooapis.com/v1/public/yql?q=' +
        CGI.escape(yql) +
        '&diagnostics=false&format=json'

  begin
    result = open(uri) {|io| JSON.parse io.read }

    open '|-', 'w' do |io|
      if io.nil?
        # In child.
        exec_or_die 'pager', '-'
      end

      # In parent.
      io.puts result.pretty_inspect
    end

  rescue => e
    $stderr.puts "Error: #{e.class}: #{e}"
  end

  $stdout.puts
end

